version = 1

[[annotations]]
path = [
    "README.*",
    "picotui/*",
    "**/widgets.rst",
]
SPDX-FileCopyrightText = [
    "2015-2021 Paul Sokolovsky <pfalcon@users.sourceforge.net>",
    "2021-2025 Stephen Arnold <sarnold@vctlabs.com>",
    "2021 simejo <simejo@disroot.org>",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "toxfile.py"
SPDX-FileCopyrightText = "Copyright (c) 2023 Masen Furer"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**"
SPDX-FileCopyrightText = [
    "2025 Stephen Arnold <sarnold@vctlabs.com>",
]
SPDX-License-Identifier = "MIT"
