{% set name = "picotui" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm

  run:
    - python >=3.6
    - setuptools-scm

test:
  imports:
    - picotui
    - picotui.widgets
    - picotui.context

about:
  home: https://github.com/sarnold/picotui
  license: MIT
  license_file: ../LICENSE
  summary: A simple text user interface (TUI) library.
  doc_url: "https://github.com/sarnold/picotui/blob/master/README.rst"
  dev_url: "https://github.com/sarnold/picotui"


extra:
  recipe-maintainers:
    - sarnold
